# Lecture 13

# Introduction to Pandas

## Week 5 Monday

## Miles Chen, PhD

#### update your environment with `uv`

run:

`uv pip install -r requirements-unix.txt` # for mac

`uv pip install -r requirements-win.txt` # for win

# Pandas

NumPy creates ndarrays that must contain values that are of the same data type.

Pandas creates dataframes. Each column in a dataframe is an ndarray. This allows us to have traditional tables of data where each column can be a different data type.

Important References:

https://pandas.pydata.org/pandas-docs/stable/reference/series.html

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html

In [1]:
import numpy as np
import pandas as pd

The basic data structure in pandas is the *series*. You can construct it in a similar fashion to making a numpy array.

The command to make a Series object is

`pd.Series(data, index=index)`

the `index` argument is optional

In [2]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
print(data)
print(type(data))

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64
<class 'pandas.Series'>

In [3]:
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

The series is printed out in a table form. The type is a Pandas Series

In [4]:
print(data.to_numpy()) # deprecated version is data.values

[0.25 0.5  0.75 1.  ]

In [5]:
print(type(data.to_numpy()))

<class 'numpy.ndarray'>

You can extract the data in the series as a numpy array.

In [6]:
print(data.index)

RangeIndex(start=0, stop=4, step=1)

In [7]:
print(type(data.index))  # the row names are known as the index

<class 'pandas.RangeIndex'>

You can subset a pandas series like other python objects

In [8]:
print(data[1])

0.5

In [9]:
print(type(data[1]))  # when you select only one value, it simplifies the object

<class 'numpy.float64'>

In [10]:
print(data[1:3])

1    0.50
2    0.75
dtype: float64

In [11]:
print(type(data[1:3]))  # slicing / selecting multiple values returns a series

<class 'pandas.Series'>

In [12]:
print(data[np.array([1, 0, 1, 2])])  # You can also do fancy indexing by subsetting w/a numpy array

1    0.50
0    0.25
1    0.50
2    0.75
dtype: float64

In [13]:
# Pandas uses a 0-based index by default. You may also specify the index values
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index = ['a', 'b', 'c', 'd'])
print(data)

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [14]:
data.to_numpy()  # the to_numpy method converts a pandas series to a numpy array

array([0.25, 0.5 , 0.75, 1.  ])

In [15]:
data.index

Index(['a', 'b', 'c', 'd'], dtype='str')

In [16]:
data["a"]  # subset with index names

np.float64(0.25)

In [17]:
data[0:2]  # slicing behavior is unchanged

a    0.25
b    0.50
dtype: float64

In [18]:
data["a":"c"] # slicing using index names includes the last value

a    0.25
b    0.50
c    0.75
dtype: float64

In [19]:
data[0] # trying to selecte only one value with an index position will not work because the index is strings

KeyError: 0

In [20]:
# creating a series from a python dictionary
# remember, dictionary construction uses curly braces {}
samp_dict = {'Tony Stark': "Robert Downey Jr.",
              'Steve Rogers': "Chris Evans",
              'Natasha Romanoff': "Scarlett Johansson",
              'Bruce Banner': "Mark Ruffalo",
              'Thor': "Chris Hemsworth",
              'Clint Barton': "Jeremy Renner"}
samp_series = pd.Series(samp_dict)
samp_series

Tony Stark           Robert Downey Jr.
Steve Rogers               Chris Evans
Natasha Romanoff    Scarlett Johansson
Bruce Banner              Mark Ruffalo
Thor                   Chris Hemsworth
Clint Barton             Jeremy Renner
dtype: str

In [21]:
print(samp_series.index) # dtype = object is for strings but allows mixed data types.

Index(['Tony Stark', 'Steve Rogers', 'Natasha Romanoff', 'Bruce Banner',
       'Thor', 'Clint Barton'],
      dtype='str')

In [22]:
samp_series.to_numpy()

array(['Robert Downey Jr.', 'Chris Evans', 'Scarlett Johansson',
       'Mark Ruffalo', 'Chris Hemsworth', 'Jeremy Renner'], dtype=object)

In [23]:
# ages during the First Avengers film (2012)
# I don't have an exact source, don't get mad at me.
age_dict = {'Thor': 1493,
              'Steve Rogers': 104,
              'Natasha Romanoff': 28,
              'Clint Barton': 41,
              'Tony Stark': 42,
              'Bruce Banner': 42}  # note that the dictionary order is not same here
ages = pd.Series(age_dict)
print(ages)

Thor                1493
Steve Rogers         104
Natasha Romanoff      28
Clint Barton          41
Tony Stark            42
Bruce Banner          42
dtype: int64

Pandas uses `pd.NA` to represent missing values. This is different from `np.nan`, which is used for numeric data. `pd.NA` is a special value that indicates a missing value in a pandas Series or DataFrame, and it can be used with any data type, including strings and integer without forcing the values into floats.

In [24]:
# Super Hero Names
hero_dict = {'Thor': pd.NA,
              'Steve Rogers': 'Captain America',
              'Natasha Romanoff': 'Black Widow',
              'Clint Barton': 'Hawkeye',
              'Tony Stark': 'Iron Man',
              'Bruce Banner': 'Hulk'}
hero_names = pd.Series(hero_dict)
print(hero_names)

Thor                            NaN
Steve Rogers        Captain America
Natasha Romanoff        Black Widow
Clint Barton                Hawkeye
Tony Stark                 Iron Man
Bruce Banner                   Hulk
dtype: str

# Creating a DataFrame

There are multiple ways of creating a DataFrame in Pandas. The next few slides show a few.

We can create a dataframe by providing a dictionary of series objects. The dictionary key becomes the column name. The dictionary values become values. The keys within the dictionaries become the index.

In [25]:
avengers = pd.DataFrame({'actor': samp_series,
                         'hero name': hero_names,
                         'age': ages})  

# the DataFrame will match the indices and sort them
print(avengers)

                               actor        hero name   age
Bruce Banner            Mark Ruffalo             Hulk    42
Clint Barton           Jeremy Renner          Hawkeye    41
Natasha Romanoff  Scarlett Johansson      Black Widow    28
Steve Rogers             Chris Evans  Captain America   104
Thor                 Chris Hemsworth              NaN  1493
Tony Stark         Robert Downey Jr.         Iron Man    42

In [26]:
print(type(avengers))  # this is a DataFrame object

<class 'pandas.DataFrame'>

The data is a list of dictionaries. Each dictionary needs to have the same set of keys, otherwise, NaNs will appear.

In [27]:
data = [{'a': 0, 'b': 0},
        {'a': 1, 'b': 2},
        {'a': 2, 'b': 5}]  
data

[{'a': 0, 'b': 0}, {'a': 1, 'b': 2}, {'a': 2, 'b': 5}]

In [28]:
print(pd.DataFrame(data, index = [1, 2, 3]))

   a  b
1  0  0
2  1  2
3  2  5

In [29]:
data2 = [{'a': 0, 'b': 0},
         {'a': 1, 'b': 2},
         {'a': 2, 'c': 5}] # mismatch of keys. NAs will appear
data2

[{'a': 0, 'b': 0}, {'a': 1, 'b': 2}, {'a': 2, 'c': 5}]

In [30]:
pd.DataFrame(data2)  # if the index argument is not supplied, it defaults to integer index start at 0

   a    b    c
0  0  0.0  NaN
1  1  2.0  NaN
2  2  NaN  5.0

You can convert a dictionary to a DataFrame. The keys form column names, and the values are lists/arrays of values. The arrays need to be of the same length.

In [31]:
data3 = {'a': [1, 2, 3],
         'b': ['x','y','z']} 
data3

{'a': [1, 2, 3], 'b': ['x', 'y', 'z']}

In [32]:
pd.DataFrame(data3)

   a  b
0  1  x
1  2  y
2  3  z

In [33]:
data4 = {'a': [1, 2, 3, 4],
         'b': ['x','y','z']} # arrays are not of the same length
pd.DataFrame(data4)

ValueError: All arrays must be of the same length

Turn a 2D Numpy array (matrix) into a DataFrame by adding column names and optionally index values.

In [34]:
data = np.random.randint(10, size = 10).reshape((5,2)) # using the old random method
print(data)

[[0 4]
 [4 7]
 [3 5]
 [4 3]
 [0 3]]

In [35]:
print(pd.DataFrame(data, columns = ["x","y"], index = ['a','b','c','d','e']))

   x  y
a  0  4
b  4  7
c  3  5
d  4  3
e  0  3

# Subsetting the DataFrame

In a DataFrame, the `.columns` attribute show the column names and the `.index` attribute show the row names.

In [36]:
print(avengers)

                               actor        hero name   age
Bruce Banner            Mark Ruffalo             Hulk    42
Clint Barton           Jeremy Renner          Hawkeye    41
Natasha Romanoff  Scarlett Johansson      Black Widow    28
Steve Rogers             Chris Evans  Captain America   104
Thor                 Chris Hemsworth              NaN  1493
Tony Stark         Robert Downey Jr.         Iron Man    42

In [37]:
print(avengers.columns)

Index(['actor', 'hero name', 'age'], dtype='str')

In [38]:
print(avengers.index)

Index(['Bruce Banner', 'Clint Barton', 'Natasha Romanoff', 'Steve Rogers',
       'Thor', 'Tony Stark'],
      dtype='str')

You can select a column using dot notation or with single square brackets.

In [39]:
avengers.actor  # extracting the column (only works if the column name has no spaces)

Bruce Banner              Mark Ruffalo
Clint Barton             Jeremy Renner
Natasha Romanoff    Scarlett Johansson
Steve Rogers               Chris Evans
Thor                   Chris Hemsworth
Tony Stark           Robert Downey Jr.
Name: actor, dtype: str

In [40]:
avengers["hero name"] # if there's a space in the column name, you'll need to use square brackets

Bruce Banner                   Hulk
Clint Barton                Hawkeye
Natasha Romanoff        Black Widow
Steve Rogers        Captain America
Thor                            NaN
Tony Stark                 Iron Man
Name: hero name, dtype: str

In [41]:
type(avengers.actor)

pandas.Series

The selected column is a Pandas Series and can be subset accordingly.

In [42]:
avengers.actor[avengers.age == 42]

Bruce Banner         Mark Ruffalo
Tony Stark      Robert Downey Jr.
Name: actor, dtype: str

In [43]:
avengers["hero name"]['Steve Rogers'] # not recommended, .loc is better

'Captain America'

# `.loc`
The `.loc` attribute can be used to subset the DataFrame using the index names.

In [44]:
avengers.loc['Thor'] # subset based on location to get a row

actor        Chris Hemsworth
hero name                NaN
age                     1493
Name: Thor, dtype: object

In [45]:
print(type(avengers.loc['Thor']))
print(type(avengers.loc['Thor'].to_numpy()))  # the values are of mixed type but is still a numpy array. 
# this is possible because it is a structured numpy array. (covered in "Python for Data Science" chapter 2)

<class 'pandas.Series'>
<class 'numpy.ndarray'>

In [46]:
print(avengers.loc[ : ,'age']) # subset based on location to get a column

Bruce Banner          42
Clint Barton          41
Natasha Romanoff      28
Steve Rogers         104
Thor                1493
Tony Stark            42
Name: age, dtype: int64

In [47]:
print(type(avengers.loc[:,'age']))  #the object is a pandas series
print(type(avengers.loc[:,'age'].to_numpy()))

<class 'pandas.Series'>
<class 'numpy.ndarray'>

In [48]:
avengers.loc['Steve Rogers','age']  # you can provide a pair of 'coordinates' to get a particular value

np.int64(104)

# `.iloc`

The `.iloc` attribute can be used to subset the DataFrame using the index position (zero-indexed).

In [49]:
avengers.iloc[3,:] # subset based on index location

actor            Chris Evans
hero name    Captain America
age                      104
Name: Steve Rogers, dtype: object

In [50]:
avengers.iloc[0, 1] # pair of coordinates

'Hulk'

# Assignment with `.loc` and `.iloc`
The `.loc` and `.iloc` attributes can be used in conjunction with assignment.

In [51]:
# set values individually
avengers.loc['Thor', 'age'] = 1500
avengers.loc['Thor', 'hero name'] = 'Thor'
avengers

                               actor        hero name   age
Bruce Banner            Mark Ruffalo             Hulk    42
Clint Barton           Jeremy Renner          Hawkeye    41
Natasha Romanoff  Scarlett Johansson      Black Widow    28
Steve Rogers             Chris Evans  Captain America   104
Thor                 Chris Hemsworth             Thor  1500
Tony Stark         Robert Downey Jr.         Iron Man    42

In [52]:
# assign multiple values at once
avengers.loc['Thor', ['hero name', 'age']] = [pd.NA, 1493]
avengers

                               actor        hero name   age
Bruce Banner            Mark Ruffalo             Hulk    42
Clint Barton           Jeremy Renner          Hawkeye    41
Natasha Romanoff  Scarlett Johansson      Black Widow    28
Steve Rogers             Chris Evans  Captain America   104
Thor                 Chris Hemsworth              NaN  1493
Tony Stark         Robert Downey Jr.         Iron Man    42

# `.loc` vs `.iloc` with numeric index

The following DataFrame has a numeric index, but it starts at 1 instead of 0.

In [53]:
data = [{'a': 11, 'b': 2},
        {'a': 12, 'b': 4},
        {'a': 13, 'b': 6}]  
df = pd.DataFrame(data, index = [1, 2, 3])
df

    a  b
1  11  2
2  12  4
3  13  6

In [54]:
df.loc[1, :] # .loc always uses the actual index.

a    11
b     2
Name: 1, dtype: int64

In [55]:
df.iloc[1, :] # .iloc always uses the position using a 0-based index.

a    12
b     4
Name: 2, dtype: int64

In [56]:
df.iloc[3, :] # using a position that doesn't exist results in an exception.

IndexError: single positional indexer is out-of-bounds

# Boolean subsetting examples with `.loc`

In [57]:
# select avengers whose age is less than 50 and greater than 40
# select the columns 'hero name' and 'age'
avengers.loc[ (avengers.age < 50) & (avengers.age > 40), ['hero name', 'age']]

             hero name  age
Bruce Banner      Hulk   42
Clint Barton   Hawkeye   41
Tony Stark    Iron Man   42

In [58]:
# Use the index of the DataFrame, treat it as a string, and select rows that start with B
avengers.loc[ avengers.index.str.startswith('B'), : ]

                     actor hero name  age
Bruce Banner  Mark Ruffalo      Hulk   42

In [59]:
# Use the index of the DataFrame, treat it as a string,
# find the character capital R. Find returns -1 if it does not find the letter
# We select rows that did not result in -1, which means it does contain a capital R
avengers.loc[ avengers.index.str.find('R') != -1, : ]

                               actor        hero name  age
Natasha Romanoff  Scarlett Johansson      Black Widow   28
Steve Rogers             Chris Evans  Captain America  104

In [60]:
avengers.loc[ avengers.index.str.contains('R'), : ]
# a simpler way to do the above using the contains method

                               actor        hero name  age
Natasha Romanoff  Scarlett Johansson      Black Widow   28
Steve Rogers             Chris Evans  Captain America  104

# Other commonly used DataFrame attributes

In [61]:
avengers.T  # the transpose

,Bruce Banner,Clint Barton,Natasha Romanoff,Steve Rogers,Thor,Tony Stark
actor,Mark Ruffalo,Jeremy Renner,Scarlett Johansson,Chris Evans,Chris Hemsworth,Robert Downey Jr.
hero name,Hulk,Hawkeye,Black Widow,Captain America,NaN,Iron Man
age,42,41,28,104,1493,42

In [62]:
avengers.dtypes # the data types contained in the DataFrame

actor          str
hero name      str
age          int64
dtype: object

In [63]:
avengers.shape # shape

(6, 3)

# Importing Data with pd.read_csv()

In [64]:
# Titanic Dataset
url = 'https://assets.datacamp.com/production/course_1607/datasets/titanic_sub.csv'
titanic = pd.read_csv(url)

In [65]:
titanic

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [66]:
titanic.shape

(891, 11)

In [67]:
titanic.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [68]:
titanic.index

RangeIndex(start=0, stop=891, step=1)

In [69]:
titanic.info() # note that Age has only 714 values indicating missing values

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Sex          891 non-null    str
 4   Age          714 non-null    float64
 5   SibSp        891 non-null    int64
 6   Parch        891 non-null    int64
 7   Ticket       891 non-null    str
 8   Fare         891 non-null    float64
 9   Cabin        204 non-null    str
 10  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(4)
memory usage: 76.7 KB

In [70]:
titanic.describe()  # displays summary statistics of the numeric variables

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200