# Lecture 14

# Pandas: Indexing, Arithmetic, Missing Values

## Week 5 Wednesday

## Miles Chen, PhD

Based on Wes McKinney's Python for Data Analysis and the Pandas Documentation

In [1]:
import numpy as np
import pandas as pd

## Series that we will use as examples

In [2]:
# note that the value after the decimal place corresponds to the letter position.
# i.e. 1.4 corresponds to d, the fourth letter.
original1 = pd.Series([1.4, 2.3, 3.1, 4.2], index = ['d','c','a','b'])
original2 = pd.Series([2.2, 3.1, 1.3, 4.4], index = ['b','a','c','d'])

In [3]:
original1 # when you create a series, the original order of the index is preserved

d    1.4
c    2.3
a    3.1
b    4.2
dtype: float64

In [4]:
# making a DataFrame with multiple series with the same index preserves the index order
pd.DataFrame({"x":original1, "x2": original1 * 2})

     x   x2
d  1.4  2.8
c  2.3  4.6
a  3.1  6.2
b  4.2  8.4

In [5]:
original2 # note that original1 and original2 have different index orders

b    2.2
a    3.1
c    1.3
d    4.4
dtype: float64

In [6]:
# because original1 and original2 have index in different order, Pandas will sort the index before putting them together
df = pd.DataFrame({"x":original1, "y": original2})
df

     x    y
a  3.1  3.1
b  4.2  2.2
c  2.3  1.3
d  1.4  4.4

In [7]:
original1.index # the index of original1 is the letters d, c, a, b in a tuple-like object

Index(['d', 'c', 'a', 'b'], dtype='str')

In [8]:
original1['d':'a'] # when slicing pandas uses the index order or original1

d    1.4
c    2.3
a    3.1
dtype: float64

In [9]:
df.index  # the index of df are the letters abcd in order

Index(['a', 'b', 'c', 'd'], dtype='str')

In [10]:
df['a':'c'] # when slicing Pandas uses the index order of the DataFrame, which has been sorted

     x    y
a  3.1  3.1
b  4.2  2.2
c  2.3  1.3

## Rearranging value

Both Series and DataFrames have the `.sort_index()` and `.sort_values()` methods which can be used to rearrange the value.

In [11]:
original2

b    2.2
a    3.1
c    1.3
d    4.4
dtype: float64

In [12]:
original2.sort_index()

a    3.1
b    2.2
c    1.3
d    4.4
dtype: float64

In [13]:
original2.sort_values()

c    1.3
b    2.2
a    3.1
d    4.4
dtype: float64

In [15]:
original2

b    2.2
a    3.1
c    1.3
d    4.4
dtype: float64

In [14]:
df

     x    y
a  3.1  3.1
b  4.2  2.2
c  2.3  1.3
d  1.4  4.4

In [16]:
df.sort_values(by = "x", ascending = False)

     x    y
b  4.2  2.2
a  3.1  3.1
c  2.3  1.3
d  1.4  4.4

# Changing the Index

The index of a Pandas Series or Pandas DataFrame is immutable and cannot be modified.

However, if you want to change the index of a series or dataframe, you can define a new index and replace the existing index of the series/DataFrame.

In [18]:
original1.index = range(4) # I replace the index of the series with this range object.

In [19]:
original1

0    1.4
1    2.3
2    3.1
3    4.2
dtype: float64

In [20]:
original1.index # We can see this has automatically become a RangeIndex object

RangeIndex(start=0, stop=4, step=1)

In [21]:
original1[1]

np.float64(2.3)

In [22]:
original1.loc[1] # behaves the same as above

np.float64(2.3)

In [23]:
original1.iloc[1] # behaves the same as above because the range index starts at 0

np.float64(2.3)

In [24]:
original1.index = range(1,5)

In [25]:
original1

1    1.4
2    2.3
3    3.1
4    4.2
dtype: float64

In [26]:
original1[1]

np.float64(1.4)

In [27]:
original1.loc[1]

np.float64(1.4)

In [28]:
original1.iloc[1] # behavior is different because range index starts at 1

np.float64(2.3)

In [29]:
original1['a'] # throws an error because 'a' is no longer part of the index and cannot be used to select values

KeyError: 'a'

In [30]:
original1.index = ['a','b','c','d'] # be careful as no restrictions regarding the meaning of the index is applied.
# in the original 'a' was associated with 3.1. This index will associate it with 1.4

In [31]:
original1

a    1.4
b    2.3
c    3.1
d    4.2
dtype: float64

In [32]:
original1['a']

np.float64(1.4)

In [33]:
original1[0] # no 'a' in the index

KeyError: 0

In [34]:
original1.index = [1, 2, 3, 4, 5] # if the object you provide is of a different length, you get a value error

ValueError: Length mismatch: Expected axis has 4 elements, new values have 5 elements

In [35]:
# similarly you can change the index of a DataFrame by defining a new object and assigning it to the index.
df.index = ['j','k','l','m']
df

     x    y
j  3.1  3.1
k  4.2  2.2
l  2.3  1.3
m  1.4  4.4

# Reindexing

Reindexing is different from just defining a new index.

Reindexing takes a current Pandas object and creates a *new* Pandas object that *conforms* to the specified index.

**Do not confuse reindexing with creating a new index for a dataframe object.**

In [36]:
original = pd.Series([1.4, 2.3, 3.1, 4.2], index = ['d','c','a','b'])

In [37]:
original

d    1.4
c    2.3
a    3.1
b    4.2
dtype: float64

In [38]:
newobj = original.reindex(['a','b','c','d','e']) # note this has an index value that doesn't exist in the original series

In [39]:
newobj  # takes the data in orignal and moves it so it conforms to the specified index
# values that do not exist for the new index get NaN

a    3.1
b    4.2
c    2.3
d    1.4
e    NaN
dtype: float64

In [40]:
# if you don't want NaN, you can specify a fill_value
newobj2 = original.reindex(['a','b','c','d','e'], fill_value = 0)
newobj2

a    3.1
b    4.2
c    2.3
d    1.4
e    0.0
dtype: float64

For ordered data like a time series, it might be desirable to fill values when reindexing

In [41]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 3, 6])
obj3

0      blue
3    purple
6    yellow
dtype: str

In [42]:
obj3.reindex(range(9))  # without any optional arguments, lots of missing values

0      blue
1       NaN
2       NaN
3    purple
4       NaN
5       NaN
6    yellow
7       NaN
8       NaN
dtype: str

In [43]:
obj3.reindex(range(9), method='ffill')
# forward-fill pushes values 'forward' until a new value is encountered

0      blue
1      blue
2      blue
3    purple
4    purple
5    purple
6    yellow
7    yellow
8    yellow
dtype: str

In [44]:
obj3.reindex(range(9), method='bfill')  
# back-fill works in the opposite direction
# there was no value at index 8 so, NaNs get filled in

0      blue
1    purple
2    purple
3    purple
4    yellow
5    yellow
6    yellow
7       NaN
8       NaN
dtype: str

## Date Ranges as Index

In [49]:
# we specify the creation of a date_index using the date_range function
# freq = 'D' creates Daily values 
date_index = pd.date_range('1/1/2010', periods=6, freq='D')
date_index

DatetimeIndex(['2010-01-01', '2010-01-02', '2010-01-03', '2010-01-04',
               '2010-01-05', '2010-01-06'],
              dtype='datetime64[us]', freq='D')

In [50]:
# we create a DataFrame with the date index
df2 = pd.DataFrame({"prices": [100, 101, np.nan, 100, 89, 88]}, index=date_index)
df2

            prices
2010-01-01   100.0
2010-01-02   101.0
2010-01-03     NaN
2010-01-04   100.0
2010-01-05    89.0
2010-01-06    88.0

In [52]:
date_index2 = pd.date_range('12/29/2009', periods=10, freq='D')  # a new date index
df2.reindex(date_index2)

            prices
2009-12-29     NaN
2009-12-30     NaN
2009-12-31     NaN
2010-01-01   100.0
2010-01-02   101.0
2010-01-03     NaN
2010-01-04   100.0
2010-01-05    89.0
2010-01-06    88.0
2010-01-07     NaN

In [53]:
df2.reindex(date_index2, method = 'bfill') 
# The value for Jan 3 isn't filled in because that NaN was not created by the reindexing process
# The NaN already existed in the data.

            prices
2009-12-29   100.0
2009-12-30   100.0
2009-12-31   100.0
2010-01-01   100.0
2010-01-02   101.0
2010-01-03     NaN
2010-01-04   100.0
2010-01-05    89.0
2010-01-06    88.0
2010-01-07     NaN

## `.reindex()` vs `.loc()`

If you don't need to fill in any missing info, then `.reindex()` and `.loc()` work very similarly.
If the new index will have values that don't exist in the current index, you need to use `reindex`.

In [54]:
obj5 = pd.DataFrame({'val':[1.4, 2.3, 3.1, 4.2]}, index = ['d','c','a','b'])
obj5

   val
d  1.4
c  2.3
a  3.1
b  4.2

In [55]:
obj5.reindex(['a','b','c','d'])

   val
a  3.1
b  4.2
c  2.3
d  1.4

In [56]:
obj5.loc[['a','b','c','d']] # works the same as reindex

   val
a  3.1
b  4.2
c  2.3
d  1.4

In [57]:
obj5.reindex(['a','b','c','d','e'])

   val
a  3.1
b  4.2
c  2.3
d  1.4
e  NaN

In [58]:
obj5.loc[['a','b','c','d','e']]  # .loc() returns an error if you give an entry in the index that doesn't exist

KeyError: "['e'] not in index"

# Dropping rows or columns

you can use `df.drop()` to remove rows (default) or columns (specify axis = 1) at certain index locations.

In [59]:
df = pd.DataFrame(np.arange(12).reshape(3,4), columns=['A', 'B', 'C', 'D'], index = ['x','y','z'])
df

   A  B   C   D
x  0  1   2   3
y  4  5   6   7
z  8  9  10  11

In [60]:
# drop rows
df.drop(['x', 'z'])

   A  B  C  D
y  4  5  6  7

In [61]:
# drop columns
df.drop(columns=['B', 'C'])

   A   D
x  0   3
y  4   7
z  8  11

In [62]:
# df.drop returns a new object and leaves df unchanged
df

   A  B   C   D
x  0  1   2   3
y  4  5   6   7
z  8  9  10  11

# Data Alignment

When performing element-wise arithmetic, Pandas will align the index values before doing the computation

In [63]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [64]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
               index=['a', 'c', 'e', 'f', 'g'])
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [65]:
pd.DataFrame({'s1':s1,'s2':s2}) # for reference

    s1   s2
a  7.3 -2.1
c -2.5  3.6
d  3.4  NaN
e  1.5 -1.5
f  NaN  4.0
g  NaN  3.1

In [66]:
s1 + s2  # returns a new series, where the indexes are the union of the indexes of s1 and s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [67]:
s1.add(s2)

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [69]:
pd.DataFrame({'s1':s1,'s2':s2})

    s1   s2
a  7.3 -2.1
c -2.5  3.6
d  3.4  NaN
e  1.5 -1.5
f  NaN  4.0
g  NaN  3.1

In [70]:
s1.sub(s2, fill_value = 0)

a    9.4
c   -6.1
d    3.4
e    3.0
f   -4.0
g   -3.1
dtype: float64

In [71]:
s1.rsub(s2, fill_value = 0) # .rsub means 'right hand subtract' sets the series in the argument as the base

a   -9.4
c    6.1
d   -3.4
e   -3.0
f    4.0
g    3.1
dtype: float64

In [72]:
s1 * s2

a   -15.33
c    -9.00
d      NaN
e    -2.25
f      NaN
g      NaN
dtype: float64

In [73]:
s1.multiply(s2, fill_value = 1)

a   -15.33
c    -9.00
d     3.40
e    -2.25
f     4.00
g     3.10
dtype: float64

For data frames with different columns, the rows and columns will be aligned

In [74]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                   index=['Ohio', 'Texas', 'Colorado'])
df1

            b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [75]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                   index=['Utah', 'Ohio', 'Texas', 'Oregon'])
df2

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [76]:
df1 + df2 
# c is in df1, but not df2
# e is in df2, but not df1
# the result returns the union of columns, but will fill in NaN for elements that do not exist in both

            b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [77]:
# if you want to fill in values that are missing, you can use df.add() and specify the fill_value
# this will perform the above operation, but instead of using NaN when it can't find a value 
# (which will return NaN),
# it will use the fill_value
df1.add(df2, fill_value = 0)
# you still get NaN if the value does not exist in either DataFrame

            b    c     d     e
Colorado  6.0  7.0   8.0   NaN
Ohio      3.0  1.0   6.0   5.0
Oregon    9.0  NaN  10.0  11.0
Texas     9.0  4.0  12.0   8.0
Utah      0.0  NaN   1.0   2.0

Arithmetic operations that can be called on DataFrames and Series are:

- `.add()`, `.radd()` and `.sub()`, `.rsub()`
- `.mul()`, `.rmul()` and `.div()`, `.rdiv()` 
- `.floordiv()`, `.rfloordiv()` (floor division `//`)
- `.pow()`, `.rpow()` (exponentiation `**`)

# Summary Stats of a DataFrame

In [78]:
df = pd.DataFrame({'one':[1.5,6.0,np.nan, 1.5,4,6, np.nan],
                   'two':[np.nan, -4.5, np.nan, -1.5, 0, -4.5, 4]},
                  index=['a', 'b', 'c', 'd','e','f','g'])
df

   one  two
a  1.5  NaN
b  6.0 -4.5
c  NaN  NaN
d  1.5 -1.5
e  4.0  0.0
f  6.0 -4.5
g  NaN  4.0

In [79]:
df.sum()  # default behavior returns column sums and skips missing values
# default behavior sums across axis 0 (sums the row)

one    19.0
two    -6.5
dtype: float64

In [80]:
df # for reference

   one  two
a  1.5  NaN
b  6.0 -4.5
c  NaN  NaN
d  1.5 -1.5
e  4.0  0.0
f  6.0 -4.5
g  NaN  4.0

In [81]:
df.sum(axis = 1) # sum across axis=1, sum across the columns and give row sums

a    1.5
b    1.5
c    0.0
d    0.0
e    4.0
f    1.5
g    4.0
dtype: float64

In [82]:
df.sum(skipna = False)

one   NaN
two   NaN
dtype: float64

In [83]:
df.mean()

one    3.8
two   -1.3
dtype: float64

In [84]:
df.mean(axis = 1)

a    1.50
b    0.75
c     NaN
d    0.00
e    2.00
f    0.75
g    4.00
dtype: float64

In [85]:
df # for reference

   one  two
a  1.5  NaN
b  6.0 -4.5
c  NaN  NaN
d  1.5 -1.5
e  4.0  0.0
f  6.0 -4.5
g  NaN  4.0

In [86]:
df.min()

one    1.5
two   -4.5
dtype: float64

In [87]:
df.idxmin()  # which row has the minimum value, also .idxmax()
# returns the first minimum, if there are multiple
# you can also specify axis

one    a
two    b
dtype: str

## Summary stats available for dataframes and series

- `count()` - number of non NA values
- `quantile()`
- `sum()`
- `mean()`
- `median()`
- `prod()`
- `var()`, `std()`

https://pandas.pydata.org/pandas-docs/stable/reference/series.html#computations-descriptive-stats

## Unique values

In [88]:
df # for reference

   one  two
a  1.5  NaN
b  6.0 -4.5
c  NaN  NaN
d  1.5 -1.5
e  4.0  0.0
f  6.0 -4.5
g  NaN  4.0

In [89]:
df.one.unique()  # shows the unique values in the order observed

array([1.5, 6. , nan, 4. ])

In [90]:
df.two.unique()

array([ nan, -4.5, -1.5,  0. ,  4. ])

In [91]:
df.unique()  # unique can only be applied to a series (a column in a dataframe)

AttributeError: 'DataFrame' object has no attribute 'unique'

In [92]:
df # for reference

   one  two
a  1.5  NaN
b  6.0 -4.5
c  NaN  NaN
d  1.5 -1.5
e  4.0  0.0
f  6.0 -4.5
g  NaN  4.0

In [93]:
df.one.nunique()  # number of non-missing unique values exist

3

In [94]:
df.one.value_counts()  # tally up counts of each value
# returns a series. the index are the unique values observed, the values are the frequencies.
# they appear in descending order of frequency

one
1.5    2
6.0    2
4.0    1
Name: count, dtype: int64

In [95]:
df.one.isin([1.5, 4.0]) # checks to see if the value has membership in a particular list
# returns a series with boolean values

a     True
b    False
c    False
d     True
e     True
f    False
g    False
Name: one, dtype: bool

In [96]:
(df.one == 1.5) | (df.one == 4.0)  # must use bitwise or. .isin() is much prefered

a     True
b    False
c    False
d     True
e     True
f    False
g    False
Name: one, dtype: bool

In [97]:
df.loc[  df.one.isin([1.5,4.0]),  ]  # can filter rows based on the .isin() membership

   one  two
a  1.5  NaN
d  1.5 -1.5
e  4.0  0.0

# filtering out missing values

In [98]:
df

   one  two
a  1.5  NaN
b  6.0 -4.5
c  NaN  NaN
d  1.5 -1.5
e  4.0  0.0
f  6.0 -4.5
g  NaN  4.0

In [99]:
df.dropna() # gets rid of any row that is not complete

   one  two
b  6.0 -4.5
d  1.5 -1.5
e  4.0  0.0
f  6.0 -4.5

In [100]:
df.dropna(how = 'all')  # only drops rows that are entirely NaN

   one  two
a  1.5  NaN
b  6.0 -4.5
d  1.5 -1.5
e  4.0  0.0
f  6.0 -4.5
g  NaN  4.0

In [101]:
# you can also use .notnull(), which is True for values that are not missing
df[df.two.notnull()]  # You can use this in conjuntion with specifying the column

   one  two
b  6.0 -4.5
d  1.5 -1.5
e  4.0  0.0
f  6.0 -4.5
g  NaN  4.0

# Filling in Missing Values

In [102]:
df

   one  two
a  1.5  NaN
b  6.0 -4.5
c  NaN  NaN
d  1.5 -1.5
e  4.0  0.0
f  6.0 -4.5
g  NaN  4.0

In [103]:
df.fillna(0) # fill in missing values with a constant

   one  two
a  1.5  0.0
b  6.0 -4.5
c  0.0  0.0
d  1.5 -1.5
e  4.0  0.0
f  6.0 -4.5
g  0.0  4.0

In [104]:
df.fillna({'one': 1000, 'two': 0})  # use a dictionary to specify values to use for each column

      one  two
a     1.5  0.0
b     6.0 -4.5
c  1000.0  0.0
d     1.5 -1.5
e     4.0  0.0
f     6.0 -4.5
g  1000.0  4.0

In [105]:
df.bfill() # backfills missing values

   one  two
a  1.5 -4.5
b  6.0 -4.5
c  1.5 -1.5
d  1.5 -1.5
e  4.0  0.0
f  6.0 -4.5
g  NaN  4.0

In [106]:
df.ffill() # forward fills missing values

   one  two
a  1.5  NaN
b  6.0 -4.5
c  6.0 -4.5
d  1.5 -1.5
e  4.0  0.0
f  6.0 -4.5
g  6.0  4.0

In [107]:
df.mean()

one    3.8
two   -1.3
dtype: float64

In [108]:
df.fillna(df.mean())  # fill na with df.mean() will fill in the column means

   one  two
a  1.5 -1.3
b  6.0 -4.5
c  3.8 -1.3
d  1.5 -1.5
e  4.0  0.0
f  6.0 -4.5
g  3.8  4.0

all of the above fillna methods have created new copies of DataFrame objects

In [109]:
df.T

       a    b   c    d    e    f    g
one  1.5  6.0 NaN  1.5  4.0  6.0  NaN
two  NaN -4.5 NaN -1.5  0.0 -4.5  4.0

In [110]:
# apparently you can only fill missing values with dictionaries/series over a column 
# so we have to do some Transpose magic
df.T.fillna(df.T.mean()).T

   one  two
a  1.5  1.5
b  6.0 -4.5
c  NaN  NaN
d  1.5 -1.5
e  4.0  0.0
f  6.0 -4.5
g  4.0  4.0

# dealing with duplicates

In [111]:
df

   one  two
a  1.5  NaN
b  6.0 -4.5
c  NaN  NaN
d  1.5 -1.5
e  4.0  0.0
f  6.0 -4.5
g  NaN  4.0

In [112]:
df.duplicated()  # sees if any of the rows are a duplicate of an earlier row

a    False
b    False
c    False
d    False
e    False
f     True
g    False
dtype: bool

In [113]:
df[~df.duplicated()]  # gets rid of the duplicated rows

   one  two
a  1.5  NaN
b  6.0 -4.5
c  NaN  NaN
d  1.5 -1.5
e  4.0  0.0
g  NaN  4.0

In [114]:
df.one.duplicated()

a    False
b    False
c    False
d     True
e    False
f     True
g     True
Name: one, dtype: bool